name: build-and-deploy-on-push

on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository | lower }}:latest
            ${{ env.REGISTRY }}/${{ github.repository | lower }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
