name: build-and-deploy-on-push

on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase image name
        run: |
          REPO_FULL_NAME="${{ github.repository }}"
          LOWERCASE_REPO_NAME=$(echo "$REPO_FULL_NAME" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$LOWERCASE_REPO_NAME" >> "$GITHUB_ENV"
          echo "Calculated image name: $LOWERCASE_REPO_NAME"

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout to k3s-homelab
        uses: actions/checkout@v4
        with:
          repository: PFlorov/k3s-homelab
          token: ${{ secrets.FLUX_PAT_K3S_HOMELAB }}
          path: k3s-homelab-repo

      - name: Install the right yq version
        uses: mikefarah/yq@v4.35.2
        id: yq

      - name: Update image tag in k3s-homelab deployment
        run: |
          cd k3s-homelab-repo

          ${{ steps.yq.outputs.path }} e '.spec.template.spec.containers[0].image = "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"' -i clusters/homelab/apps/blog/blog-deployment.yaml

          cat cluster/homelab/apps/blog/blog-deployment.yaml

      - name: Commit and push changes to k3s-homelab
        run: |
          cd k3s-homelab-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@user.noreply.github.com"
          git add clusters/homelab/apps/blog/blog-deployment.yaml
          git commit -m "chore(blog): update blog image to ${{ github.sha }}"
          git push
